style: update mat-card components
eclipse-dataspaceconnector/DataDashboard pull request #259
Opened 2024-12-10 08:26 UTC by s-damith

## What this PR changes/adds

Refactor Angular Material mat-card components to enhance UI and functionality on the introduction page.

## Why it does that

Add padding to the internal elements of the card components and utilize standardized card component sub-elements.

![localhost_4200_introduction(lap) (2)](https://github.com/user-attachments/assets/1c3d38f6-ebd1-47e2-970a-5f2e7d13d1a7)

## Linked Issue(s)

Closes #258 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2024-12-18 09:25 UTC, timdah requested changes
I would also propose to set the font of mat-card (`font-family: 'Open Sans'`) for a uniform typeface.

2024-12-18 09:25 UTC, timdah commented on src/modules/edc-demo/components/introduction/introduction.component.html
> +    <mat-card-content>
```suggestion
      <mat-card-header>
        <mat-card-title>Eclipse Dataspace Connector</mat-card-title>
      </mat-card-header>
      <mat-card-content>
```

Using `mat-card-title` to follow material design.

2024-12-18 09:25 UTC, timdah commented on src/modules/edc-demo/components/introduction/introduction.component.html
> +    <mat-card-content>
```suggestion
    <mat-card-header>
      <mat-card-title>EDC Data Dashboard (this application)</mat-card-title>
    </mat-card-header>
    <mat-card-content>
```

2024-12-18 09:25 UTC, timdah commented on src/modules/edc-demo/components/introduction/introduction.component.scss
>      padding-right: 20px;
Remove padding-right as well for symmetrical look.

2024-12-19 10:00 UTC, timdah requested changes
Added the suggested font-family. The rest looks good to me.

2024-12-19 11:09 UTC, s-damith commented on src/modules/edc-demo/components/introduction/introduction.component.scss
>  mat-card {
Hi! Replace the `<h1>` tag with `mat-card-title`. It applies the 'Open Sans' font family by default, so there's no need to apply the font family again.

![Screenshot 2024-12-19 at 4 35 07 PM](https://github.com/user-attachments/assets/f81dfa76-0c65-4eb7-95f1-cbd86bce3a86)

2024-12-19 11:13 UTC, s-damith commented on src/modules/edc-demo/components/introduction/introduction.component.scss
>  mat-card {
Yeah, you are right. But the description text uses a different font type. Therefore, I added the font family to mat-card. Thanks.

2024-12-19 11:15 UTC, timdah commented on src/modules/edc-demo/components/introduction/introduction.component.scss
>  mat-card {
Hi! True, but the paragraphs inside `mat-card-content` still have the wrong font. For the sake of simplicity, I would therefore set it for the whole card.

2024-12-19 11:16 UTC, timdah approved these changes

2024-12-19 12:23 UTC, merged